import Head from 'next/head';
import TodoPage from './todo';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Knitto Tekstil Indonesia</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<TodoPage />
		</div>
	);
}
